# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppLoglikelihood <- function(D, h, n) {
    .Call(`_xbadzupaR_CppLoglikelihood`, D, h, n)
}

make_pilot <- function(D, h, n) {
    .Call(`_xbadzupaR_make_pilot`, D, h, n)
}

rcpp_hello_world <- function() {
    .Call(`_xbadzupaR_rcpp_hello_world`)
}

